package com.almacen.view;

import com.almacen.utilities.PanelCustom;
import com.almacen.utilities.Tools;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class PantallaPrincipal extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos, ampm, dia, mes, anio;
    Calendar calendario;
    Thread h1;

    Tools tools = new Tools();

    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);

        h1 = new Thread(this);
        h1.start();

        this.btnMenuCiber.setSelected(true);

        new PanelCustom(pnlContenedorPaneles, new pnlCiber());
    }

    private void fechaHora() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? ""
                    + calendario.get(Calendar.HOUR_OF_DAY) : "0"
                    + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? ""
                + calendario.get(Calendar.MINUTE) : "0"
                + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? ""
                + calendario.get(Calendar.SECOND) : "0"
                + calendario.get(Calendar.SECOND);
        dia = calendario.get(Calendar.DAY_OF_MONTH) > 9 ? ""
                + calendario.get(Calendar.DAY_OF_MONTH) : "0"
                + calendario.get(Calendar.DAY_OF_MONTH);
        mes = calendario.get(Calendar.MONTH) > 9 ? ""
                + calendario.get(Calendar.MONTH) : "0"
                + calendario.get(Calendar.MONTH);
        anio = calendario.get(Calendar.YEAR) > 9 ? ""
                + calendario.get(Calendar.YEAR) : "0"
                + calendario.get(Calendar.YEAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainerPrincipal = new javax.swing.JPanel();
        pnlBarraSuperior = new javax.swing.JPanel();
        lblTutulo = new javax.swing.JLabel();
        lblHoralFecha = new javax.swing.JLabel();
        pnlMenuLateral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMenuCiber = new com.almacen.utilities.BotonCustom();
        btnMenuRegalos = new com.almacen.utilities.BotonCustom();
        btnMenuBotanero = new com.almacen.utilities.BotonCustom();
        btnMenuUsuarios = new com.almacen.utilities.BotonCustom();
        btnMenuConfiguracion = new com.almacen.utilities.BotonCustom();
        btnMenuProveedor = new com.almacen.utilities.BotonCustom();
        btnMenuAcercaDe = new com.almacen.utilities.BotonCustom();
        pnlContenedorPaneles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContainerPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnlBarraSuperior.setBackground(new java.awt.Color(0, 32, 96));
        pnlBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTutulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTutulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTutulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTutulo.setText("SISTEMA DE ALMACÉN");
        pnlBarraSuperior.add(lblTutulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 430, 40));

        lblHoralFecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHoralFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblHoralFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoralFecha.setText("FECHA");
        pnlBarraSuperior.add(lblHoralFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 475, 40));

        pnlMenuLateral.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuLateral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        pnlMenuLateral.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 230, 180));

        btnMenuCiber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconCiber.png"))); // NOI18N
        btnMenuCiber.setText("CIBER");
        btnMenuCiber.setColorNormal(new java.awt.Color(0, 32, 96));
        btnMenuCiber.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuCiber.setFocusPainted(false);
        btnMenuCiber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuCiber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuCiber.setIconTextGap(30);
        btnMenuCiber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuCiberMousePressed(evt);
            }
        });
        btnMenuCiber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCiberActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuCiber, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 43));

        btnMenuRegalos.setBackground(new java.awt.Color(238, 161, 8));
        btnMenuRegalos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconRegalos.png"))); // NOI18N
        btnMenuRegalos.setText("REGALOS");
        btnMenuRegalos.setColorNormal(new java.awt.Color(238, 161, 8));
        btnMenuRegalos.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuRegalos.setFocusPainted(false);
        btnMenuRegalos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuRegalos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuRegalos.setIconTextGap(30);
        btnMenuRegalos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuRegalosMousePressed(evt);
            }
        });
        btnMenuRegalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegalosActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuRegalos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 43));

        btnMenuBotanero.setBackground(new java.awt.Color(238, 161, 8));
        btnMenuBotanero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconBotanero.png"))); // NOI18N
        btnMenuBotanero.setText("BOTANERO");
        btnMenuBotanero.setColorNormal(new java.awt.Color(238, 161, 8));
        btnMenuBotanero.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuBotanero.setFocusPainted(false);
        btnMenuBotanero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBotanero.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuBotanero.setIconTextGap(30);
        btnMenuBotanero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuBotaneroMousePressed(evt);
            }
        });
        btnMenuBotanero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBotaneroActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuBotanero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 43));

        btnMenuUsuarios.setBackground(new java.awt.Color(238, 161, 8));
        btnMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconUsuario.png"))); // NOI18N
        btnMenuUsuarios.setText("USUARIOS");
        btnMenuUsuarios.setColorNormal(new java.awt.Color(238, 161, 8));
        btnMenuUsuarios.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuUsuarios.setFocusPainted(false);
        btnMenuUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuUsuarios.setIconTextGap(30);
        btnMenuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuUsuariosMousePressed(evt);
            }
        });
        btnMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUsuariosActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 43));

        btnMenuConfiguracion.setBackground(new java.awt.Color(238, 161, 8));
        btnMenuConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconEngrane.png"))); // NOI18N
        btnMenuConfiguracion.setText("CONFIGURACIÓN");
        btnMenuConfiguracion.setColorNormal(new java.awt.Color(238, 161, 8));
        btnMenuConfiguracion.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuConfiguracion.setFocusPainted(false);
        btnMenuConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuConfiguracion.setIconTextGap(30);
        btnMenuConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuConfiguracionMousePressed(evt);
            }
        });
        btnMenuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuConfiguracionActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 43));

        btnMenuProveedor.setBackground(new java.awt.Color(238, 161, 8));
        btnMenuProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconProveedor.png"))); // NOI18N
        btnMenuProveedor.setText("PROVEEDORES");
        btnMenuProveedor.setColorNormal(new java.awt.Color(238, 161, 8));
        btnMenuProveedor.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuProveedor.setFocusPainted(false);
        btnMenuProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuProveedor.setIconTextGap(30);
        btnMenuProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuProveedorMousePressed(evt);
            }
        });
        btnMenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProveedorActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 43));

        btnMenuAcercaDe.setBackground(new java.awt.Color(238, 161, 8));
        btnMenuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almacen/assets/iconInfo.png"))); // NOI18N
        btnMenuAcercaDe.setText("ACERCA DE");
        btnMenuAcercaDe.setColorNormal(new java.awt.Color(238, 161, 8));
        btnMenuAcercaDe.setColorPressed(new java.awt.Color(0, 32, 96));
        btnMenuAcercaDe.setFocusPainted(false);
        btnMenuAcercaDe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuAcercaDe.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenuAcercaDe.setIconTextGap(30);
        btnMenuAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuAcercaDeMousePressed(evt);
            }
        });
        btnMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAcercaDeActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnMenuAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 230, 43));

        pnlContenedorPaneles.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedorPaneles.setLayout(new javax.swing.BoxLayout(pnlContenedorPaneles, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout pnlContainerPrincipalLayout = new javax.swing.GroupLayout(pnlContainerPrincipal);
        pnlContainerPrincipal.setLayout(pnlContainerPrincipalLayout);
        pnlContainerPrincipalLayout.setHorizontalGroup(
            pnlContainerPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlContainerPrincipalLayout.createSequentialGroup()
                .addComponent(pnlMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlContenedorPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContainerPrincipalLayout.setVerticalGroup(
            pnlContainerPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerPrincipalLayout.createSequentialGroup()
                .addComponent(pnlBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlContainerPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContainerPrincipalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pnlMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContainerPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(pnlContenedorPaneles, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainerPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainerPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUsuariosActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlUsuarios());
        tools.buttonSelected(btnMenuUsuarios, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuUsuariosActionPerformed

    private void btnMenuCiberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCiberActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlCiber());
        tools.buttonSelected(btnMenuCiber, btnMenuRegalos, btnMenuBotanero,
                btnMenuUsuarios, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuCiberActionPerformed

    private void btnMenuRegalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegalosActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlRegalos());
        tools.buttonSelected(btnMenuRegalos, btnMenuCiber, btnMenuBotanero,
                btnMenuUsuarios, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuRegalosActionPerformed

    private void btnMenuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuConfiguracionActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlConfiguracion());
        tools.buttonSelected(btnMenuConfiguracion, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuUsuarios, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuConfiguracionActionPerformed

    private void btnMenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProveedorActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlAcercaDe());
        tools.buttonSelected(btnMenuProveedor, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuUsuarios, btnMenuConfiguracion);
    }//GEN-LAST:event_btnMenuProveedorActionPerformed

    private void btnMenuBotaneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBotaneroActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlBotanero());
        tools.buttonSelected(btnMenuBotanero, btnMenuCiber, btnMenuRegalos,
                btnMenuUsuarios, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuBotaneroActionPerformed

    private void btnMenuCiberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCiberMousePressed
        tools.buttonPressed(btnMenuCiber, btnMenuRegalos, btnMenuBotanero,
                btnMenuUsuarios, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuCiberMousePressed

    private void btnMenuRegalosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuRegalosMousePressed
        tools.buttonPressed(btnMenuRegalos, btnMenuCiber, btnMenuBotanero,
                btnMenuUsuarios, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuRegalosMousePressed

    private void btnMenuBotaneroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBotaneroMousePressed
        tools.buttonPressed(btnMenuBotanero, btnMenuCiber, btnMenuRegalos,
                btnMenuUsuarios, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuBotaneroMousePressed

    private void btnMenuUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUsuariosMousePressed
        tools.buttonPressed(btnMenuUsuarios, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuConfiguracion, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuUsuariosMousePressed

    private void btnMenuConfiguracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuConfiguracionMousePressed
        tools.buttonPressed(btnMenuConfiguracion, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuUsuarios, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuConfiguracionMousePressed

    private void btnMenuProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuProveedorMousePressed
        tools.buttonPressed(btnMenuProveedor, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuUsuarios, btnMenuConfiguracion);
    }//GEN-LAST:event_btnMenuProveedorMousePressed

    private void btnMenuAcercaDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuAcercaDeMousePressed
        tools.buttonPressed(btnMenuConfiguracion, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuUsuarios, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuAcercaDeMousePressed

    private void btnMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAcercaDeActionPerformed
        new PanelCustom(pnlContenedorPaneles, new pnlConfiguracion());
        tools.buttonSelected(btnMenuConfiguracion, btnMenuCiber, btnMenuRegalos,
                btnMenuBotanero, btnMenuUsuarios, btnMenuProveedor);
    }//GEN-LAST:event_btnMenuAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.almacen.utilities.BotonCustom btnMenuAcercaDe;
    private com.almacen.utilities.BotonCustom btnMenuBotanero;
    private com.almacen.utilities.BotonCustom btnMenuCiber;
    private com.almacen.utilities.BotonCustom btnMenuConfiguracion;
    private com.almacen.utilities.BotonCustom btnMenuProveedor;
    private com.almacen.utilities.BotonCustom btnMenuRegalos;
    private com.almacen.utilities.BotonCustom btnMenuUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHoralFecha;
    private javax.swing.JLabel lblTutulo;
    private javax.swing.JPanel pnlBarraSuperior;
    private javax.swing.JPanel pnlContainerPrincipal;
    private javax.swing.JPanel pnlContenedorPaneles;
    private javax.swing.JPanel pnlMenuLateral;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            fechaHora();
            lblHoralFecha.setText(
                    hora + ":" + minutos + ":" + segundos + " " + ampm + " - "
                    + dia + "/" + mes + "/" + anio);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }

        }
    }
}
